Cudos 1120: Improve contract funding at deployment
CudoVentures/cudo-framework pull request #102
Opened 2022-06-23 13:37 UTC by Holymir

- Funding at deployment is now handled by cudos-contrac.js
- Default denominator added
-  Documentation updated

2022-06-24 09:02 UTC, ealeksandrov-LimeChain commented on packages/blast-core/lib/cudos-contract.js
> +const { parseCoins } = require('@cosmjs/stargate')
We can require `parseCoins` from cudosjs

2022-06-27 09:05 UTC, ealeksandrov-LimeChain commented on packages/blast-core/README.md
> -const { coin } = require('@cosmjs/stargate')
You may also need to remove stargate dependency from template/package.json

2022-07-08 06:46 UTC, maptuhec approved these changes

2022-07-18 12:39 UTC, ealeksandrov-LimeChain requested changes
In `packages/blast-core/template/package.json` there is a dependency (`"@cosmjs/stargate": "^0.28.3"`) that will make the user install an unused package on `npm install` of a new project. Please confirm that this package is not used and if so - remove it.

2022-07-19 11:25 UTC, ealeksandrov-LimeChain approved these changes

2022-07-19 14:38 UTC, merged