Cudos 1021: Create bre unit tests
CudoVentures/cudo-framework pull request #106
Opened 2022-08-08 12:37 UTC by ealeksandrov-LimeChain

2022-08-29 14:52 UTC, maptuhec requested changes

2022-08-29 14:52 UTC, maptuhec commented on packages/blast-core/lib/bre.test.js
> +const mockedInstantiateTx = {
Remove all mocked data from the test file, and create a separate one with only the mocked data. Leave the test file clean with only tests for better review

2022-09-01 11:43 UTC, maptuhec approved these changes

2022-09-09 04:23 UTC, Holymir approved these changes

2022-09-09 12:47 UTC, merged