Cudos 553: Prepare cudos-blast for plugin development
CudoVentures/cudo-framework pull request #81
Opened 2022-04-27 12:23 UTC by ealeksandrov-LimeChain

- Split 'cudos-blast' npm package into 'root' and 'blast-core'
- global functions are available in 1 globally exposed object that represents a 'blast runtime environment'
- adjusted tests for the new architecture

2022-05-17 11:42 UTC, tgntr approved these changes

2022-05-17 11:42 UTC, tgntr commented on packages/blast-core/template/scripts/deploy.js
> +  const [alice, bob] = await bre.getSigners()
would it be better to require bre for readability?

2022-05-25 12:53 UTC, maptuhec requested changes
Review the workflow for publishing

2022-06-01 06:31 UTC, Holymir approved these changes

2022-06-02 05:50 UTC, maptuhec approved these changes

2022-06-02 05:54 UTC, tgntr approved these changes

2022-06-02 08:19 UTC, merged